GET http://localhost:3000/

###

GET http://localhost:3000/shoes

###

GET http://localhost:3000/shoes/1


###

POST http://localhost:3000/add
Content-Type: application/json

    {
        "id": "",
        "title": "LOREM IPSUM",
        "brand": "LOREM IPSUM",
        "price": 99999999,
        "image": "https://www.hoka.com/dw/image/v2/BCQW_PRD/on/demandware.static/-/Sites-HOKA-EMEA-master/default/dw0e02d7de/images/1123157-FRYL_1.jpg?sw=1110&sh=1141&sm=fit&sfrm=png&bgcolor=ffffff"
    }

###

PUT http://localhost:3000/edit/1
Content-Type: application/json

    {
        "title": "EDITED",
        "brand": "EDITED",
        "price": "0000000",
        "image": "https://www.hoka.com/dw/image/v2/BCQW_PRD/on/demandware.static/-/Sites-HOKA-EMEA-master/default/dw0e02d7de/images/1123157-FRYL_1.jpg?sw=1110&sh=1141&sm=fit&sfrm=png&bgcolor=ffffff"
    }

###

DELETE http://localhost:3000/delete/6